# Generated by Django 2.1.7 on 2019-03-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_spareproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('serial', models.CharField(choices=[('AA', 'Kiev'), ('AH', 'Donetsk')], default='AA', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilitaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('serial', models.CharField(choices=[('B1', 'Military law enforcement service of the AFU'), ('E1', 'Military units of engineering troops of the AFU')], default='E1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerСar',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='station.Transport')),
                ('hatch', models.BooleanField(default=False)),
                ('seats', models.IntegerField(default=2)),
            ],
            bases=('station.transport',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='station.Transport')),
                ('lifting_gear', models.BooleanField(default=False)),
                ('pallet_places', models.IntegerField(default=2)),
                ('height', models.FloatField(default='1.0')),
                ('width', models.FloatField(default='1.0')),
            ],
            bases=('station.transport',),
        ),
        migrations.AlterModelOptions(
            name='spareproxy',
            options={'ordering': ['name']},
        ),
    ]
